### ISSUE TITLE
Add an exception handler on MqttServer to be aware of error happening outside the MqttEndpoint

### ISSUE THREAD

**Issue by vietj** [vert-x3/vertx-mqtt-server#15]

**Comment by ppatierno** [comment]
@vietj why this revert adding an exception handler ? Should we have a discussion or at least a PR to review before committing changes like this ?

**Comment by vietj** [comment]
`Handler<AsyncResult<T>>` is a construct that can be called once and is similar to a method return or throwing an exception. In this case `Handler<T>` will be called for each new valid connection. So it is not the same semantic.

Furthermore, the user code is not much interested in invalid connections, these are discarded before reaching the handler. This behavior is the same for instance on an `HttpServer` that process an invalid HTTP request.
 
What should have been discussed is rather the previous change that changed `Handler<T>` to `Handler<AsyncResult<T>>`.
