### ISSUE TITLE
Default endpoint settings 

### ISSUE THREAD

**Issue by Sammers21** [vert-x3/vertx-mqtt-server#23]
By default when sending SUBSCRIBE server doesn't respond with a SUBACK packet. To enable responding we need to execute:
```java
 endpoint.subscriptionAutoAck(true);
```
and the same situation with a PUBLISH packet.

But according to MQTT spec 3.1.1. [Article 3.8.4 SUBSCRIBE Response](http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/csprd02/mqtt-v3.1.1-csprd02.html#_Toc385349803): "when the Server receives a SUBSCRIBE Packet from a Client, the Server MUST respond with a SUBACK Packet". So, by default, it does not respond.

And my suggestion is that enable subscriptionAutoAck by default.

**Comment by ppatierno** [comment]
The MQTT server component is a server not a full broker. It means that it handles MQTT connections and coming messages providing the application all the API for replying to clients. It's up to the application sending the SUBACK after receiving the SUBSCRIBE message. An MQTT broker could be developed using this MQTT server. I added the auto ack on subscribe just as additional feature.

**Comment by Sammers21** [comment]
@ppatierno, may be "full broker" would be a great additional feature? :-D

**Comment by ppatierno** [comment]
@Sammers21 there is already a Vert.x MQTT broker and some effort to move it using the Vert.x MQTT server https://github.com/GruppoFilippetti/vertx-mqtt-broker/issues/11
