### ISSUE TITLE
If the server need a CONNECT packet repetitions check

### ISSUE THREAD

**Issue by ioprotocol** [vert-x3/vertx-mqtt-server#32]
does here need a CONNECT repetitions check like this?
```java
 /**
   * Handle the MQTT message received by the remote MQTT client
   *
   * @param msg message to handle
   */
  synchronized void handleMessage(Object msg) {

    // handling directly native Netty MQTT messages, some of them are translated
    // to the related Vert.x ones for polyglotization
    if (msg instanceof io.netty.handler.codec.mqtt.MqttMessage) {

      io.netty.handler.codec.mqtt.MqttMessage mqttMessage = (io.netty.handler.codec.mqtt.MqttMessage) msg;

      DecoderResult result = mqttMessage.decoderResult();
      if (result.isFailure()) {
        chctx.pipeline().fireExceptionCaught(result.cause());
        return;
      }
      if (!result.isFinished()) {
        chctx.pipeline().fireExceptionCaught(new Exception("Unfinished message"));
        return;
      }

      // does here need a CONNECT repetitions check like this?
      if(endpoint == null && mqttMessage.fixedHeader().messageType() != MqttMessageType.CONNECT) {
        endpoint.close();
      }
      if(endpoint != null && mqttMessage.fixedHeader().messageType() == MqttMessageType.CONNECT) {
        endpoint.close();
      }
     ...
```

**Comment by ppatierno** [comment]
Yes. Thanks for reporting. The second check can be done in the "switch/case" on CONNECT packet. I'll take a look to fix that.

**Comment by ppatierno** [comment]
I have investigated and it's not a real issue because all the handleXXXX methods have a checkConnected() which has this kind of check.

**Comment by ioprotocol** [comment]
@ppatierno All  handleXXXX methods have do this kind of check except handleConnect method not, because the handleConnect method have a little difference with other handleXXXX methods, Consider this situation: if a client send CONNECT packet twice within one net connection, of course this is not permitted by mqtt 3.1.1 specification for client, but the handleConnect method in MqttConnection class will create another new MqttEndpointImpl Object,  which is not conform to specification,  While in top level when write a mqtt broker, there will be no method to do this kind of check

**Comment by ioprotocol** [comment]
All handleXXXX methods have do this kind of check except handleConnect method not, because the handleConnect method have a little difference with other handleXXXX methods, Consider this situation: if a client send CONNECT packet twice within one net connection, of course this is not permitted by mqtt 3.1.1 specification for client, but the handleConnect method in MqttConnection class will create another new MqttEndpointImpl Object, which is not conform to specification, While in top level when write a mqtt broker, there will be no method to do this kind of check 

    On Tuesday, July 18, 2017 3:30 PM, Paolo Patierno <notifications@github.com> wrote:
 

 I have investigated and it's not a real issue because all the handleXXXX methods have a checkConnected() which has this kind of check.—
