### ISSUE TITLE
Add test case for "Wrong message type"

### ISSUE THREAD

**Issue by ppatierno** [vert-x3/vertx-mqtt-server#8]
In order to test the "Wrong message type" case in the MqttConnection class we need to send a poisoned MQTT packed with an unknown message type.

**Comment by krishnarb3** [comment]
@ppatierno 
I tried to create a MqttWrongMessageTypeTest but I'm stuck at publishing a message with unknown message type.
I tried using the same code as MqttBadClientTest class's createPublishMessage method but the MqttFixedHeader constructor requires a MqttMessageType. I am not able to set it as anything other than the ones in the enum.
Could you help me out? Thanks.

**Comment by ppatierno** [comment]
my idea was not using the awesome encoding classes from Netty MQTT codec but just sends raw bytes. For example, the PINGREQ packet is just 2 bytes that are pretty simple to generate without the Netty MQTT codec but just reading the MQTT spec. For example, the PINGREQ has the second byte to 0 (remaining length) so for making it "bad" just put the first byte at 0 as well, because the first nibble (4 bits) of the first byte are the packet type and 0 isn't a valid one.

**Comment by ppatierno** [comment]
Added with 9d2f912997fd3b12f47cc8a2d432544cc23d6c5b
Btw it's disabled for now because it needs a change in Netty (see this my PR https://github.com/netty/netty/pull/6985)
