### ISSUE TITLE
NullPointer when message couldn't be parsed

### ISSUE THREAD

**Issue by codepitbull** [vert-x3/vertx-mqtt-server#9]
There is a problem in MqttServerImpl when the incoming message couldn't be parsed.
In safeObject right after `if (msg instanceof io.netty.handler.codec.mqtt.MqttMessage)` there is the following statement: `switch (mqttMessage.fixedHeader().messageType())` it accesses the message content without evaluating MqttMessage.decoderResult first. As all elements of a message are empty in case of a decoding error you will receive a NullPointerException.

**Comment by ppatierno** [comment]
Fair enough thanks ! Do you have a test case for that ? Did it happen to you during the MQTT server usage ?

**Comment by codepitbull** [comment]
We are currently using it from Unity (m2mqtt, I guess you know the library ;) ). There we generated a UUID as clientidentifier. Under the hood that caused `invalid clientIdentifier: 20c41644-2166-4098-ab11-16a7b0384b4e`. So creating a message with that clientIdentifier should be a good reproducer.
I hope to work a little more on this but I am currently on the road.

**Comment by ppatierno** [comment]
Fixed by 1f582292e7027407cb3715bb5e4a385337847a3c
